// Auto-generated by scripts/generate-gallery.js - do not edit by hand.
// Gallery is built from files in public/images named {category}_{descriptive}.webp

export const GALLERY_IMAGES: { src: string; category: string; alt: string }[] = [
  { src: "/images/solar-farms_moonrise-solar.webp", category: "Solar Farms", alt: "Moonrise Solar" },
  { src: "/images/solar-farms_site-solar-farm-new.webp", category: "Solar Farms", alt: "Site Solar Farm New" },
  { src: "/images/solar-farms_solar-farm-dusk.webp", category: "Solar Farms", alt: "Solar Farm Dusk" },
  { src: "/images/solar-farms_solar-farm-golden.webp", category: "Solar Farms", alt: "Solar Farm Golden" },
  { src: "/images/solar-farms_solar-farm-road.webp", category: "Solar Farms", alt: "Solar Farm Road" },
  { src: "/images/solar-farms_solar-farm-sunset.webp", category: "Solar Farms", alt: "Solar Farm Sunset" },
  { src: "/images/solar-farms_sunset-panels-close.webp", category: "Solar Farms", alt: "Sunset Panels Close" },
  { src: "/images/solar-farms_sunset-panels-wide.webp", category: "Solar Farms", alt: "Sunset Panels Wide" },
  { src: "/images/installation_hero-construction.webp", category: "Installation", alt: "Hero Construction" },
  { src: "/images/installation_install-panel-closeup.webp", category: "Installation", alt: "Install Panel Closeup" },
  { src: "/images/installation_install-panel-detail.webp", category: "Installation", alt: "Install Panel Detail" },
  { src: "/images/installation_install-panel-ground.webp", category: "Installation", alt: "Install Panel Ground" },
  { src: "/images/installation_install-site-crew.webp", category: "Installation", alt: "Install Site Crew" },
  { src: "/images/installation_install-site-overview.webp", category: "Installation", alt: "Install Site Overview" },
  { src: "/images/installation_install-worker-active.webp", category: "Installation", alt: "Install Worker Active" },
  { src: "/images/installation_install-workers-carry.webp", category: "Installation", alt: "Install Workers Carry" },
  { src: "/images/installation_mounting-structure.webp", category: "Installation", alt: "Mounting Structure" },
  { src: "/images/installation_panel-blue-sky.webp", category: "Installation", alt: "Panel Blue Sky" },
  { src: "/images/installation_solar-panels-close.webp", category: "Installation", alt: "Solar Panels Close" },
  { src: "/images/installation_workers-install.webp", category: "Installation", alt: "Workers Install" },
  { src: "/images/civil-works_cable-laying-team.webp", category: "Civil Works", alt: "Cable Laying Team" },
  { src: "/images/civil-works_cable-trench.webp", category: "Civil Works", alt: "Cable Trench" },
  { src: "/images/civil-works_civil-cable-work.webp", category: "Civil Works", alt: "Civil Cable Work" },
  { src: "/images/civil-works_civil-foundation.webp", category: "Civil Works", alt: "Civil Foundation" },
  { src: "/images/civil-works_civil-groundwork.webp", category: "Civil Works", alt: "Civil Groundwork" },
  { src: "/images/civil-works_civil-site-work.webp", category: "Civil Works", alt: "Civil Site Work" },
  { src: "/images/civil-works_civil-trench-crew.webp", category: "Civil Works", alt: "Civil Trench Crew" },
  { src: "/images/civil-works_trench-team.webp", category: "Civil Works", alt: "Trench Team" },
  { src: "/images/team_team-group-large.webp", category: "Team", alt: "Team Group Large" },
  { src: "/images/team_team-lineup.webp", category: "Team", alt: "Team Lineup" },
  { src: "/images/team_team-site.webp", category: "Team", alt: "Team Site" },
];

export const GALLERY_CATEGORIES = ["All", ...["Solar Farms","Installation","Civil Works","Team"]];
