/**
 * Generates lib/gallery-images.generated.ts from image files in public/images.
 *
 * Naming convention: {category}_{descriptive}.webp
 * - category: solar-farms | installation | civil-works | team
 * - descriptive: hyphenated slug (used for alt text, e.g. "solar-farm-road" → "Solar farm road")
 *
 * Add or remove images in public/images; run "npm run generate:gallery" or "npm run build"
 * to regenerate the array. Counts and categories stay in sync automatically.
 */

const fs = require("fs");
const path = require("path");

const GALLERY_DIR = path.join(__dirname, "..", "public", "images");
const OUT_FILE = path.join(__dirname, "..", "lib", "gallery-images.generated.ts");

const CATEGORY_MAP = {
  "solar-farms": "Solar Farms",
  installation: "Installation",
  "civil-works": "Civil Works",
  team: "Team",
};

const CATEGORY_ORDER = ["Solar Farms", "Installation", "Civil Works", "Team"];

function slugToAlt(slug) {
  return slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(" ");
}

function generate() {
  if (!fs.existsSync(GALLERY_DIR)) {
    fs.writeFileSync(
      OUT_FILE,
      `// Generated by scripts/generate-gallery.js - no public/images folder found.
export const GALLERY_IMAGES: { src: string; category: string; alt: string }[] = [];
export const GALLERY_CATEGORIES = ["All", ...${JSON.stringify(CATEGORY_ORDER)}];
`
    );
    console.log("No public/images folder; wrote empty GALLERY_IMAGES.");
    return;
  }

  const files = fs.readdirSync(GALLERY_DIR);
  const knownCategories = new Set(Object.keys(CATEGORY_MAP));
  const entries = [];

  for (const file of files) {
    const ext = path.extname(file).toLowerCase();
    if (ext !== ".webp" && ext !== ".jpg" && ext !== ".jpeg" && ext !== ".png") continue;

    const base = path.basename(file, ext);
    const firstUnderscore = base.indexOf("_");
    if (firstUnderscore <= 0) continue;

    const categoryKey = base.slice(0, firstUnderscore);
    if (!knownCategories.has(categoryKey)) continue;

    const descriptive = base.slice(firstUnderscore + 1);
    const category = CATEGORY_MAP[categoryKey];
    const alt = slugToAlt(descriptive.replace(/_/g, "-"));
    entries.push({
      src: `/images/${file}`,
      category,
      alt,
    });
  }

  // Sort by category order, then by src
  entries.sort((a, b) => {
    const ai = CATEGORY_ORDER.indexOf(a.category);
    const bi = CATEGORY_ORDER.indexOf(b.category);
    if (ai !== bi) return ai - bi;
    return a.src.localeCompare(b.src);
  });

  const lines = entries.map(
    (e) => `  { src: "${e.src}", category: "${e.category}", alt: "${e.alt.replace(/"/g, '\\"')}" },`
  );

  const content = `// Auto-generated by scripts/generate-gallery.js - do not edit by hand.
// Gallery is built from files in public/images named {category}_{descriptive}.webp

export const GALLERY_IMAGES: { src: string; category: string; alt: string }[] = [
${lines.join("\n")}
];

export const GALLERY_CATEGORIES = ["All", ...${JSON.stringify(CATEGORY_ORDER)}];
`;

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, content, "utf8");
  console.log(`Generated ${entries.length} gallery images → ${path.relative(path.join(__dirname, ".."), OUT_FILE)}`);
}

generate();
